name: List S3 Bucket

on:
  workflow_dispatch:   

env:
  ECR_REPOSITORY: backend

permissions:
  id-token: write      
  contents: read

jobs:
  list-s3:
    #runs-on: [self-hosted, k3s]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          # Update package index
          sudo apt-get update

          # Install Docker
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

          # Install AWS CLI v2
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

          # Install unzip and other utilities if missing
          sudo apt-get install -y unzip curl git build-essential python3

          # Verify tools
          which docker
          which aws
          which git
          python3 --version

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::795488789172:role/github-action-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      #  Pull ANY public image
      - name: Pull public image
        run: docker pull nginx:latest

      #  Tag it for ECR
      - name: Tag image
        run: |
          docker tag nginx:latest \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      # Push to ECR
      - name: Push to ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
      
      - name: List S3 bucket
        run: |
          aws s3 ls
