name: Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: [self-hosted, linux, eks]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print sample message
        run: |
          echo "Successfully Completed!!" 
